// Code generated by "stringer -type=VoteResult"; DO NOT EDIT.

// 此处代码是通过stringer生成
package quorum

import "strconv"

func _() { // 该函数不会被调用，仅用于编译器检查使用
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	// 强制校验VotePending的值必须是1，否则编译器会报错
	var x [1]struct{}
	_ = x[VotePending-1]
	_ = x[VoteLost-2]
	_ = x[VoteWon-3]
}

const _VoteResult_name = "VotePendingVoteLostVoteWon"

var _VoteResult_index = [...]uint8{0, 11, 19, 26}

// 返回数字对应的英文含义
// 1为VotePending，则截取0-11个字符
func (i VoteResult) String() string {
	i -= 1
	if i >= VoteResult(len(_VoteResult_index)-1) {
		return "VoteResult(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _VoteResult_name[_VoteResult_index[i]:_VoteResult_index[i+1]]
}
